### PR TITLE
Check it please

### PR DESCRIPTION
**Pull request by maelfosso**
Hi,

We have done. Could you check it please.

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi Team,
I can't signup/login. Kindly let me know if I'm missing anything on slack.
If it's missing, kindly add and resubmit.

**Comment by maelfosso** [comment]
Hi @inhaq 

We resubmit a code review request after updating the seed.
Use **Microverse Student** to Sign In, please. Don't forget to follow the README instructions, please.

Regards.

**Review by inhaq — CHANGES_REQUESTED** [review]
> Eventbrite which allows users to create events and then manage user signups

This is from the Odin project first line.
Thanks for letting me know. Although I was asking about user signups. I can do seedings but where will new user signup? I can only see login before that users will need to sign up.
You can do one thing to let user signed up and log in at the same time as there is no password by adding functionality to login feature.

**Comment by fabienrakotomampiandra** [comment]
Good morning @inhaq !
Thanks for the advise. I'm gonna fix it and let you know.

**Review by inhaq — CHANGES_REQUESTED** [review]
Good job on fixing login issue. It's working fine now.
I wasn't able to create an event, it's ending up in[ this error](https://snag.gy/WB5bVu.jpg).

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi, [this is how invitation ending up on my machine](https://snag.gy/vdXl8Y.jpg). Kindly look into the using of the app from a normal user point of view. In case, there is some exceptional case, kindly handle it. So, I can move on to look into coding practices, etc.

**Comment by fabienrakotomampiandra** [comment]
@inhaq the error is due to invitations table not found. But on my side it works well. So how can I ensure that the table is well created on your side. Please can you run migration again or if the error persist rollback and run again.

**Comment by inhaq** [comment]
Actually, I tried twice and also if you don't seed after migration, it pops up an error. It shouldn't show error and instead, it should handle the exception of when there is no user in DB.

**Comment by maelfosso** [comment]
Hello, 

We just updated the code. Please after pulling it, please run `rails db:drop db:create db:migrate
`
And start from scratch by creating your own user. You could run `rails db:seed` to populate the db

**Review by inhaq — APPROVED** [review]
Good work Team, it's 👍🏻
I'll suggest adding tests as well.
Good luck with the next project.

**Comment by maelfosso** [comment]
Thank you.

**Pull request merged**
